# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyMovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SDWebImage', '~> 5.0'
pod 'SwiftLoader', '1.0.0'


  # Pods for MyMovieApp

  target 'MyMovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyMovieAppUITests' do
    # Pods for testing
  end

end
